image: node:latest

stages:
  - deploy

cache:
  key:
    files:
      - package-lock.json
  paths:
    - node_modules/

deploy:
  stage: deploy
  before_script:
    - apt-get update && apt-get install -y curl
    - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
    - export NVM_DIR="$HOME/.nvm"
    - '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"'
    - '[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"'
    - nvm install 16.14.0
  script:
    - npm install
    - npm run dev
